#!/usr/bin/env python3
"""
Fast Windows / CareSix host reachability for GCS dual-machine.

Uses Tailscale peer Online flag when available (no 100s SSH hang).
Exit: 0 = online-ish, 1 = offline/unknown (still prints JSON line).
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

WIN_IP = "100.92.159.73"
WIN_HOSTHINTS = ("3900x", "3900")
SSH_HOST = f"kyled@{WIN_IP}"
WOW = Path(__file__).resolve().parents[2]
RECEIPTS = (
    Path.home()
    / "Library"
    / "Application Support"
    / "UAH"
    / "butler"
    / "control-plane"
    / "receipts"
    / "wow"
)


def tailscale_peer() -> dict:
    ts = shutil.which("tailscale")
    if not ts:
        return {"ok": False, "source": "none", "online": False, "error": "tailscale not on PATH"}
    try:
        r = subprocess.run(
            [ts, "status", "--json"],
            capture_output=True,
            text=True,
            timeout=8,
        )
        if r.returncode != 0:
            return {"ok": False, "source": "tailscale", "online": False, "error": (r.stderr or r.stdout)[:200]}
        data = json.loads(r.stdout)
        peers = data.get("Peer") or {}
        for _k, v in peers.items():
            ips = v.get("TailscaleIPs") or []
            hn = (v.get("HostName") or "").lower()
            if WIN_IP in ips or any(h in hn for h in WIN_HOSTHINTS):
                return {
                    "ok": True,
                    "source": "tailscale",
                    "online": bool(v.get("Online")),
                    "hostname": v.get("HostName"),
                    "ips": ips,
                    "last_seen": v.get("LastSeen"),
                    "relay": v.get("Relay"),
                }
        return {"ok": True, "source": "tailscale", "online": False, "error": "peer not found"}
    except Exception as e:
        return {"ok": False, "source": "tailscale", "online": False, "error": str(e)}


def ssh_probe(timeout: int = 8) -> dict:
    try:
        r = subprocess.run(
            [
                "ssh",
                "-o",
                "BatchMode=yes",
                "-o",
                f"ConnectTimeout={timeout}",
                SSH_HOST,
                "echo SSH_OK",
            ],
            capture_output=True,
            text=True,
            timeout=timeout + 5,
        )
        ok = r.returncode == 0 and "SSH_OK" in (r.stdout or "")
        return {
            "ok": ok,
            "source": "ssh",
            "online": ok,
            "rc": r.returncode,
            "stderr": (r.stderr or "")[:160],
        }
    except Exception as e:
        return {"ok": False, "source": "ssh", "online": False, "error": str(e)}


def probe(force_ssh: bool = False) -> dict:
    ts = tailscale_peer()
    result = {
        "when": datetime.now(timezone.utc).isoformat(),
        "host": SSH_HOST,
        "ip": WIN_IP,
        "tailscale": ts,
        "ssh": None,
        "verdict": "OFFLINE",
    }
    if ts.get("online"):
        result["verdict"] = "ONLINE_TS"
        if force_ssh:
            result["ssh"] = ssh_probe()
            if result["ssh"].get("online"):
                result["verdict"] = "ONLINE_SSH"
            else:
                result["verdict"] = "TS_ONLINE_SSH_FAIL"
    else:
        # offline on TS — still optional one quick SSH (usually fail fast)
        if force_ssh:
            result["ssh"] = ssh_probe(timeout=5)
            if result["ssh"].get("online"):
                result["verdict"] = "ONLINE_SSH"
    return result


def write_receipt(result: dict) -> Path:
    RECEIPTS.mkdir(parents=True, exist_ok=True)
    day = datetime.now().strftime("%Y-%m-%d")
    path = RECEIPTS / f"WINDOWS_SCH_REACHABILITY_{day}.md"
    v = result["verdict"]
    ts = result.get("tailscale") or {}
    body = [
        f"# Windows SCH reachability — {day}",
        "",
        f"**Verdict:** `{v}`",
        f"**When (UTC):** {result['when']}",
        f"**Host:** `{result['host']}`",
        "",
        "## Tailscale",
        "",
        f"- online: **{ts.get('online')}**",
        f"- hostname: `{ts.get('hostname')}`",
        f"- last_seen: `{ts.get('last_seen')}`",
        f"- ips: `{ts.get('ips')}`",
        f"- error: `{ts.get('error')}`",
        "",
        "## SSH",
        "",
        f"```json\n{json.dumps(result.get('ssh'), indent=2)}\n```",
        "",
        "## Rule",
        "",
        "- Do **not** claim SCH Ready unless `verdict` is `ONLINE_SSH` and task states were read live.",
        "- `OFFLINE` / `ONLINE_TS` without SSH = tasks **unproven**.",
        "",
        f"Generated by `windows_reachability.py` · vault `{WOW}`",
        "",
    ]
    path.write_text("\n".join(body), encoding="utf-8")
    # also stamp INDEX pointer
    index = WOW / "00-Index" / "WINDOWS_REACHABILITY_latest.md"
    index.write_text("\n".join(body), encoding="utf-8")
    return path


def main() -> int:
    force = "--ssh" in sys.argv
    result = probe(force_ssh=force)
    path = write_receipt(result)
    print(json.dumps({"verdict": result["verdict"], "receipt": str(path), **{k: result[k] for k in ("host", "when")}}))
    print(f"receipt -> {path}")
    print(f"verdict={result['verdict']} online_ts={bool((result.get('tailscale') or {}).get('online'))}")
    return 0 if result["verdict"].startswith("ONLINE") else 1


if __name__ == "__main__":
    raise SystemExit(main())
